export { QueryPlanner, resolveSignals, signalLabel, computeCompositeScore } from './planner.js'
export { classifyQuery } from './classifier.js'
export { mergeAndRank, minMaxNormalize, dedupKey, normalizeRRF, normalizePPR } from './merger.js'
export type { NormalizedResult } from './merger.js'
export { assemble } from './assemble.js'
export { IndexedRunner } from './runners/indexed.js'
export { searchWithContext } from './context-search.js'
export type { ContextSearchOpts, ContextPassage, ContextSearchResponse } from './context-search.js'
